#En:Don't touch this value
#Fr: Ne pas modifier cette valeur 
version: 0.3
#En:Maximal number Redstone blink authorized during the "Delay" period
#Fr:Nombre maximal de clignotement de redstone autorise pendant la periode "Delay"
MaxImpulsion: 150
#En: Time (in second) before the reset of the variable "MaxImpulsion"
#Fr:Temp (en secondes) avant de reset la premiere variable
Delay: 300
#En:You need it prevent an admin?
#Fr:Faut t'il prevenir un admin?
NotifyAdmins: true
#En:Write the text you want in the sign
#Fr:Ecrire le texte a mettre sur les panneaux
Sign:
  Line1: 'The RedstonClock'
  Line2: 'Are'
  Line3: '&4prohibited'
  Line4: ''

#En:The list of worlds on which the plugin is disabled separate by "/", put a fake name if nothing
#Fr: La list des mondes sur lequel le plugin est desactive separe par des "/", mettre un faut non si aucun 
IgnoreWorlds: redstoneWorld/survie

#En:The list of Region on which the plugin is disabled separate by "/", put a fake name if nothing
#Fr: La list des Regions sur lequel le plugin est desactive separe par des "/", mettre un faut non si aucun 
IgnoreRegion: redstone/admins

Msg:
  default:
    prefix: '&bAntiRedstoneClock &9&l> &r&b '
    error: '&4AntiRedstoneClock &l> &r&c '
    no_permission: '&4Erreur &9&l> &r&bYou dont have permission to do that!'
    command_use: '&4SnowBallWar &l> &r&cCommand usage: &6/arc $commande'
  message:
    MsgToAdmin: 'Redstone clock disable in x:$X y:$Y Z:$Z. In the world $World'
    unknownCmd: 'Unknown command. Type "/help" for help.'
    reloadSuccess: 'Reload Success!'
    newValueInConfig: 'The new value of $setting is $value'
    RedStoneClockListHeader: 'RedstoneClockList: $page'
    RedStoneClockListFooter: ''
  Exception:
    duplicate_object: 'This list already contains this redstone'
